server:
  port: 8080
  servlet:
    context-path: /bootcamp
spring:
  datasource:
    drive-class-name: org.postgresql.Driver
    url: postgres://ygrpqrvqfpbraw:be1082dde2b4c8f0e1240473f3aa23e5ba7b72f5c08e52767a8b7863cc84a911@ec2-54-224-194-214.compute-1.amazonaws.com:5432/d7523nj2uvnbof
    username: ygrpqrvqfpbraw
    password: be1082dde2b4c8f0e1240473f3aa23e5ba7b72f5c08e52767a8b7863cc84a911
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o bootcamp DIO - Santander